import os
import re

def to_camel_case(snake_str):
    """Convert kebab-case or snake-case to camelCase."""
    components = re.split(r'[-_]', snake_str)
    return components[0] + ''.join(x.title() for x in components[1:])

def convert_svg_attrs(svg_string):
    """Convert common SVG attributes to React camelCase."""
    # List of common problematic attributes
    attrs = [
        "stroke-width", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit",
        "stroke-dasharray", "stroke-dashoffset", "fill-opacity", "fill-rule",
        "clip-path", "clip-rule", "stop-color", "stop-opacity", "font-family",
        "font-size", "font-weight", "text-anchor", "vector-effect", "pointer-events"
    ]
    
    for attr in attrs:
        # Match attr="something"
        pattern = f'\\b{attr}='
        camel_attr = to_camel_case(attr)
        svg_string = re.sub(pattern, f"{camel_attr}=", svg_string)
        
    return svg_string

def transpile_to_react(svg_path: str, component_name: str, output_dir: str):
    """
    Read a processed plain SVG, convert its attributes, and wrap it in a React component template.
    """
    if not os.path.exists(svg_path):
        raise FileNotFoundError(f"SVG not found at {svg_path}")
        
    with open(svg_path, "r", encoding="utf-8") as fh:
        raw_svg = fh.read()
        
    # Strip the XML declaration: <?xml version="1.0" ... ?>
    raw_svg = re.sub(r'<\?xml[^>]*\?>', '', raw_svg).strip()
    
    # SVG tag might have random heights/widths. Let's make it responsive.
    # Replace <svg ... > with <svg viewBox="..." width="100%" height="100%" {...props}>
    react_svg = convert_svg_attrs(raw_svg)
    
    # We want to keep the viewBox but allow custom sizes and props
    # Just do a rough extraction of the viewBox
    viewbox_match = re.search(r'viewBox="([^"]+)"', react_svg)
    viewbox_str = viewbox_match.group(1) if viewbox_match else "0 0 100 100"
    
    # Strip the entire opening <svg ...> tag and closing </svg>
    react_svg = re.sub(r'<svg[^>]*>', '', react_svg)
    react_svg = react_svg.replace('</svg>', '').strip()
    
    template = f"""import React from 'react';

/**
 * AUTO-GENERATED COMPONENT: {component_name}
 * Do not edit this file directly. 
 * Re-run the Inkscape pipeline (python build_assets.py) to update.
 */

export interface {component_name}Props extends React.SVGProps<SVGSVGElement> {{
    size?: number | string;
}}

export const {component_name}: React.FC<{component_name}Props> = ({{ 
    size = '100%', 
    ...props 
}}) => {{
    return (
        <svg 
            viewBox="{viewbox_str}" 
            width={{size}} 
            height={{size}} 
            shapeRendering="geometricPrecision"
            {{...props}}
        >
            {react_svg}
        </svg>
    );
}};
"""

    os.makedirs(output_dir, exist_ok=True)
    out_file = os.path.join(output_dir, f"{component_name}.tsx")
    
    with open(out_file, "w", encoding="utf-8") as fh:
        fh.write(template)
        
    print(f"[{os.path.basename(__file__)}] Transpiled React Component: {out_file}")

